## 배포용
## 추후 RDS 연결 시 다시 확인
server:
  port: 5000
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${rds.url}
    username: ${rds.username}
    password: ${rds.password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100

  data:
    redis:
      port: ${redis.port}
      host:
    mongodb:
      uri: ${mongodb.uri}

logging:
  level:
    web: debug

slack:
  webhook:
    url: ${slack.webhook.url}

github:
  client-id: ${github.client-id}
  client-secret: ${github.client-secret}
  access-token: ${github.access-token}

management:
  endpoint:
    health:
      show-components: always
  #      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    git:
      mode: full
  server:
    port: 8090


aws:
  access:
    key: ${aws.access.key}
  secret:
    key: ${aws.secret.key}
  s3:
    bucket: ${aws.s3.bucket}